name: DeployToAzure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  resourceGroupName: GitHubExampleRG

jobs:

  deploy:

    runs-on: unbutu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         enable-AzPSSession: true

      - name: Create the ResourceGroup
        uses: Azure/powershell@v2
        with:
         inlineScript: New-AzResourceGroup -Name ${{ env.resourceGroupName }} -Location East US -Force
         azPSVersion: latest

      - name: Build the bicep file into arm
        uses: Azure/cli@v2.1.0
        with:
         inlineScript: az bicep build --file main.bicep --outfile ./main.json
                  
      - name: Deploy arm
        uses: Azure/arm-deploy@v2
        with:
         scope: resourcegroup
         resourceGroupName: ${{ env.resourceGroupName }}
         template: main.json
         parameters: storageAccountPrefix=ghaction
         deploymentName: "gh${{github.run_id}}"
         


              

      
